  
  # Find all the available rules by running:
  # swiftlint rules
  
disabled_rules:
  - nesting
  - cyclomatic_complexity
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
  
opt_in_rules:
  - empty_count
included:
  - notes
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self

force_cast: warning
force_try: warning
  
line_length: 120
function_body_length: 50
type_body_length: 300
file_length: 600
  
type_name:
  min_length: 3
  max_length: 40
  excluded:
    - ID
    - UI
    
identifier_name:
  min_length: 2
  allowed_symbols: "_"
  excluded:
    - ==
    - id
    - URL
    - url
    - key
    - any
    - lhs
    - rhs
    
reporter: "xcode"
