# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  ENV['FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT'] = '600'

  desc "Build an .ipa file for manual distribution (e.g. via diawi)"
  lane :build_diawi do
    build_app(
      scheme: "notes",
      method: "ad-hoc",
      configuration: "Release"
    )
  end

  desc "Run SwiftLint"
  lane :lint do
    swiftlint(
      strict: true,
      reporter: "emoji",
      executable: "~/.mint/*/swiftlint",
      raise_if_swiftlint_error: true
    )
  end

  desc "Build and Test iOS poject"
  lane :build_and_test do
    scan(
      device: "iPhone 13",
      result_bundle: true
    )
  end

end
