# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Build an .ipa file for manual distribution (e.g. via diawi)"
  lane :build_diawi do
    build_app(
      scheme: "notes",
      method: "ad-hoc",
      configuration: "Release"
    )
  end

  desc "Build and Test iOS poject"
  lane :build_and_test do
    ENV['FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT'] = '600'
    scan(
      device: "iPhone 13",
      cloned_source_packages_path: "cached/spm",
      derived_data_path: "cached/derived_data",
      result_bundle: true
    )
  end

end
