# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Build an .ipa file for manual distribution (e.g. via diawi)"
  lane :build_diawi do
    build_app(
      scheme: "notes",
      method: "ad-hoc",
      configuration: "Release"
    )
  end

  desc "Build and Test iOS poject"
  lane :build_and_test do |options|
    scan(
      scheme: "notes",
      skip_package_dependencies_resolution: options[:skip_package_dependencies_resolution],
      result_bundle: true
    )
  end

end
