name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build_test:
    name: Build & Test
    runs-on: macos-latest
    
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.6.0
        with: 
          access_token: ${{ github.token }}
    
      - name: Bootstrap
        uses: actions/bootstrap

      - name: Restore Cache
        uses: actions/cache@v3
          id: cache
          with:
            path: .build
            key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
            restore-keys: ${{ runner.os }}-spm-
          
      - name: Build & Test -- No Cache
        if: steps.cache.outputs.cache-hit != 'true'
        run: bundle exec fastlane build_and_test

      - name: Build & Test -- Cached
        if: steps.cache.outputs.cache-hit == 'true'
        run: bundle exec fastlane build_and_test skip_package_dependencies_resolution:true

      - name: Generate Report
        uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: fastlane/test_output/notes.xcresult
          title: Test Results
        if: success() || failure()
        
