name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build_test:
    name: Build & Test
    runs-on: macos-latest
    
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.6.0
        with: 
          access_token: ${{ github.token }}

      - name: Git Checkout
        uses: actions/checkout@v3
    
      - name: Bootstrap
        uses: ./.github/.actions/bootstrap

      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: cached
          key: ${{ runner.os }}-build-and-packages-${{ hashFiles('**/Package.resolved') }}
  
      - name: Build & Test
        run: bundle exec fastlane build_and_test

      - name: Generate Report
        uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: fastlane/test_output/notes.xcresult
          title: Test Results
        if: success() || failure()
        
