name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.6.0
        with: 
          access_token: ${{ github.token }}
    
      - name: Git - Checkout
        uses: actions/checkout@v3
      
      - name: Setup - Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
        
      - name: Setup - Ruby & Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.6' # Not needed with a .ruby-version file
          bundler-cache: true   # Runs 'bundle install' and caches installed gems automatically
          
      - name: Run Tests
        run: xcodebuild clean test -project "notes.xcodeproj" -scheme "notes" -destination "platform=iOS Simulator,name=iPhone 13,OS=latest"
      - name: Build App
        run: xcodebuild -project "notes.xcodeproj" -scheme "notes" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
      
